name: SE333_CI
on:
  push:
    branches:
      - main

jobs:
  SE333_CI_JOB:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: setupJava
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64

      - name: Install Linter
        run: |
          sudo apt-get update
          sudo apt-get install -y maven


      - name: Run Checkstyle
        run: |
          mvn clean validate \
            -Dcheckstyle.consoleOutput=true \
            -Dcheckstyle.failOnViolation=false

      - name: Upload Checkstyle Result
        if: always()
        uses: actions/upload-artifact@v3
        with:
            name: checkstyle-report
            path: target/checkstyle-result.xml

      - name: Run Maven Test
        run: mvn clean test

      - name: Jacoco Report
        run: mvn jacoco:report
        if: always()

      - name: Upload Coverage Report

        if: always()
        uses: actions/upload-artifact@v3
        with:
            name: jacoco-report
            path: target/site/jacoco/
